### ISSUE TITLE
Graphviz SVGs cause exception

### ISSUE THREAD

**Issue by szacchino** [ismay/coarse-cli#2]
Hi,

trying with several SVG as generated by dot/graphviz (i.e.: https://graphviz.gitlab.io/_pages/Gallery/directed/cluster.svg) causes the following exception

```
/usr/local/lib/node_modules/coarse-cli/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:206
          throw new DOMException("The object can not be found here.", "NotFoundError");
          ^
NotFoundError: The object can not be found here.
    at SVGSVGElementImpl.insertBefore (/usr/local/lib/node_modules/coarse-cli/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:206:17)
    at SVGSVGElementImpl.replaceChild (/usr/local/lib/node_modules/coarse-cli/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:269:10)
    at SVGSVGElement.replaceChild (/usr/local/lib/node_modules/coarse-cli/node_modules/jsdom/lib/jsdom/living/generated/Node.js:307:45)
    at coarse (/usr/local/lib/node_modules/coarse-cli/node_modules/coarse/lib/index.js:102:11)
    at fn (/usr/local/lib/node_modules/coarse-cli/bin/index.js:71:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/coarse-cli/bin/index.js:75:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

I've just used `coarse <input> <output>` without any further options.

**Comment by ismay** [comment]
Moved to https://github.com/ismay/coarse/issues/13, where the error is originating
